---
title: "peekbank_explore"
author: "Martin Zettersten"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

# Preliminaries

Load packages. 

```{r}

library(tidyverse)
library(here)

knitr::opts_chunk$set(cache = TRUE, arn = FALSE,warning=FALSE, message = FALSE,cache.lazy = FALSE)
```

# Load data and initial processing

```{r}
aoi_data_joined <- readRDS(here("power_analysis","peekbank","data","aoi_data_joined.Rds"))

aoi_data_joined<- aoi_data_joined %>%
  mutate(aoi_new=case_when(
    aoi=="target" ~ 1,
    aoi=="distractor"~0,
    aoi=="missing"~ NaN
  )) %>%
  mutate(aoi_new=ifelse(is.nan(aoi_new),NA,aoi_new))

```

# Inspect candidate dataset Yurovsky et al. 2017

Focus on baseline looking for familiar vs. novel vs. mutual-exclusivity trials

```{r}
attword <- aoi_data_joined %>%
  filter(dataset_name=="attword_processed")

#average data by participants
summarize_by_subj_by_condition <- attword %>%
  group_by(subject_id,age, condition,t_norm) %>%
  summarize(N=sum(!is.na(aoi_new)),
            mean_accuracy=mean(aoi_new,na.rm=TRUE))

summarize_across_subj_by_condition <- summarize_by_subj_by_condition %>%
  group_by(condition,t_norm) %>%
  summarize(N=sum(!is.na(mean_accuracy)),
            accuracy=mean(mean_accuracy,na.rm=TRUE),
            sd_accuracy=sd(mean_accuracy,na.rm=TRUE),
            se_accuracy=sd_accuracy/sqrt(N))

# ggplot(summarize_across_subj_by_condition,aes(x=t_norm,y=accuracy,color=condition))+
#   geom_line(data=summarize_by_subj_by_condition,aes(y=mean_accuracy,color=as.factor(subject_id),group=as.factor(subject_id)),alpha=0.2)+
#   geom_smooth(method="gam",se=FALSE)+
#   geom_vline(xintercept=0)+
#   geom_vline(xintercept=300,linetype="dotted")+
#   geom_hline(yintercept=0.5,linetype="dashed")+
#   theme(legend.position="none")+
#   facet_wrap(~condition)

baseline_by_subj_by_trial <- attword %>%
  filter(t_norm<=300) %>%
  group_by(subject_id,age, condition,trial_id) %>%
  summarize(N=sum(!is.na(aoi_new)),
            mean_accuracy=mean(aoi_new,na.rm=TRUE),
            prop_missing=mean(is.na(aoi_new)))

summarize_baseline_by_subj_condition <- baseline_by_subj_by_trial %>%
  filter(prop_missing<=0.5) %>% #at least half the data present
  group_by(subject_id,age, condition) %>%
  summarize(
    accuracy=mean(mean_accuracy,na.rm=T))

#All children
ggplot(summarize_baseline_by_subj_condition,aes(accuracy))+
  geom_histogram()+
  facet_wrap(~condition)
#just younger than 18 months
ggplot(filter(summarize_baseline_by_subj_condition,age<18),aes(accuracy))+
  geom_histogram()+
  facet_wrap(~condition)
```

